"""Help copy shown by the plugin GUI."""

HELP_TEXT = (
    "Scientific calculations were generated by StructLens. "
    "This plugin visualizes the imported analysis and does not recompute metrics."
)
