"""Small panel factory kept separate from the data reader."""

from __future__ import annotations

from typing import Any


def show_dialog(controller: Any, parent: Any = None) -> Any:
    import tkinter as tk
    from tkinter import ttk

    window = tk.Toplevel(parent) if parent is not None else tk.Tk()
    window.title("StructLens-PyMOL")
    ttk.Label(
        window,
        text="Scientific calculations were generated by StructLens.\nThis plugin visualizes the imported analysis.",
    ).pack(padx=16, pady=16)
    ttk.Button(window, text="Reset StructLens view", command=controller.reset).pack(padx=16, pady=8)
    return window
