"""Small panel factory kept separate from the data reader."""

from __future__ import annotations

from typing import Any


def show_dialog(controller: Any, parent: Any = None) -> Any:
    import tkinter as tk
    from tkinter import ttk

    window = tk.Toplevel(parent) if parent is not None else tk.Tk()
    window.title("StructLens-PyMOL")
    ttk.Label(
        window,
        text="Scientific calculations were generated by StructLens.\nThis plugin visualizes the imported analysis without recomputation.",
    ).pack(padx=16, pady=16)
    ttk.Label(window, text="v0.3 views: Residue Evidence · Interactions · Sites · Vectors").pack(padx=16, pady=4)
    ttk.Button(window, text="Refresh imported evidence", command=lambda: _refresh(controller)).pack(padx=16, pady=4)
    ttk.Button(window, text="Reset StructLens view", command=controller.reset).pack(padx=16, pady=8)
    return window


def _refresh(controller: Any) -> None:
    visualization = getattr(controller, "visualization", None)
    if visualization is None:
        return
    visualization.create_interaction_selections()
